spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.37.199.99:3306/weeked?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Xiaoguang.guo123!
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 500
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    database: 0
    #   host: 129.28.150.115
    #   port: 6379
    #   password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    cluster:
      nodes:
        - 116.198.160.80:7000
        - 116.198.160.80:7001
        - 116.198.160.80:7002
        - 116.198.160.80:7003
        - 116.198.160.80:7004
        - 116.198.160.80:7005
